name: summit-pdf-api
region: sfo
services:
  - name: web
    git:
      branch: main
      repo_clone_url: ${_REPO_URL}  # Will be replaced by actual repository URL
    build_command: pip install -r requirements.txt
    run_command: gunicorn summit_project.wsgi:application --bind 0.0.0.0:8080 --workers 3
    envs:
      - key: DJANGO_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DJANGO_DEBUG
        scope: RUN_TIME
        value: "False"
      - key: PYTHONUNBUFFERED
        scope: RUN_TIME
        value: "1"
      - key: DJANGO_ALLOWED_HOSTS
        scope: RUN_TIME
        value: ${APP_DOMAIN}  # Will be automatically set by DigitalOcean
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs  # Smallest instance size, can be scaled up
    health_check:
      http_path: /api/compress/
      initial_delay_seconds: 30
    routes:
      - path: /
    source_dir: /